myproj/myapp/urls.py
from django.urls import path
from . import views

app_name = "fileapp"

urlpatterns = [
    path("",views.index),
    path("upload", views.send_files,name="uploads")
]

myproj/myproj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls",namespace="fileapp"))
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproj/myapp/models.py
from django.db import models

# Create your models here.
class myuploadfile(models.Model):
    f_name = models.CharField(max_length=255)
    myfiles = models.FileField(upload_to="")

    def __str__(self):
        return self. f_name

myproj/myapp/views.py
from django.shortcuts import render,HttpResponse

from . models import myuploadfile

# Create your views here.
def index(request):
    return render(request, "index.html")

def send_files(request):
    if request.method == "POST" :
        name = request.POST.get("filename")
        myfile = request.FILES.getlist("uploadfoles")
        for f in myfile:
            myuploadfile(f_name=name,myfiles=f).save()
        
        return HttpResponse("file submited")

myproj/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'fileapp:uploads' %}" method="post" enctype="multipart/form-data">
        <input type="text" name="filename" placeholder="enter your filename">
        <input type="file" multiple name ="uploadfoles">
        {% csrf_token %}
        <button type="submit">File upload</button>
    </form>
</body>
</html>